default: &default
  adapter: <%= ENV.fetch('CABLE_ADAPTER', 'any_cable') %>

development:
  <<: *default

test:
  <<: *default
  channel_prefix: evil_chat_test

production:
  <<: *default
  channel_prefix: evil_chat_production
