default: &default
  adapter: <%= ENV.fetch("CABLE_ADAPTER") { ENV["ANY_CABLE"] == "1" ? "any_cable" : "async" } %>

development:
  <<: *default

test:
  <<: *default
  channel_prefix: evil_chat_test

production:
  <<: *default
  channel_prefix: evil_chat_production
