# List of available adapters: async, any_cable
development:
  adapter: <%= ENV.fetch("CABLE_ADAPTER", "any_cable") %>

test:
  adapter: test

production:
  adapter: <%= ENV.fetch("CABLE_ADAPTER", "any_cable") %>
  channel_prefix: evil_chat_production
