default: &default
  # List of the available adapters: async, any_cable
  adapter: <%= ENV.fetch("CABLE_ADAPTER") { "any_cable" } %>

development:
  <<: *default

test:
  adapter: async
  channel_prefix: evil_chat_test

production:
  <<: *default
  channel_prefix: evil_chat_production
